### ISSUE TITLE
Automatically search for internal ctors without needing extra config

### ISSUE THREAD

**Issue by robdmoore** [MRCollective/AutofacContrib.NSubstitute#1]

**Comment by centur** [comment]
Hi, is there any way to explicitly configure Autosubstitute so it will instruct autofac to use `internal` constructors for classes ? 

As far as I can see - there is an extension point that allows me to affect the Autofac's `ContainerBuilder` before container construction - via special `AutoSubstitute` ctor:
```
public AutoSubstitute(Action<ContainerBuilder> builderModifier)
```
But I can't find any suitable sample that would hint how I can modify containerBuilder so it would start to search for internal ctors. Everything is focused on a single type registration with Constructor via
`.FindConstructorsWith(new NonPublicConstructorFinder())` or `DefaultConstructorFinder` with parameters.

But this would override all registrations that are made from registration source `NSubstituteRegistrationHandler`, right ? 

Any hints on how I can keep using AutoSubstitute for ctor parameters, but instruct autofac to look for public AND internal constructors for the classes being resolved ?
