### ISSUE TITLE
Support for Substitute.ForPartsOf<>()

### ISSUE THREAD

**Issue by pratikf** [MRCollective/AutofacContrib.NSubstitute#19]
There is already a convenience method for calling Substitute.For<>() and Provide() together. Is it possible to add one for ForPartsOf<>() to create and register partial substitutes?
http://nsubstitute.github.io/help/partial-subs/

Thanks!

**Comment by robdmoore** [comment]
Sounds reasonable.

Feel free to submit a pull request and I'll be happy to merge and push out to NuGet :)

**Comment by twsouthwick** [comment]
Once #41 is in, I'm happy to add this
