### ISSUE TITLE
Support for .NET 4.5 and read only collections

### ISSUE THREAD

**Issue by Jason-eCargo** [MRCollective/AutofacContrib.NSubstitute#25]
Are there any plans to target .NET framework 4.5 and the new read only collection classes?

**Comment by robdmoore** [comment]
No specific plans to do anything with this library, but pull requests are welcome.

Off the top of my head I'm not really sure what .net 4.5 support means (it targets 4 currently so will work with 4.5) and same for readonly collections.

**Comment by Jason-eCargo** [comment]
I am currently using Autofac and AutoSubstitute to unit test the module.

Suppose that the class `ParamCollection` and interface `IParam `is registered with a Autofac module and there are multiple classes which implements `IParam`.
`public class ParamCollection { public ParamCollection(IReadOnlyCollection<IParam> parameters) ... }`

In the unit tests AutoSubstitute is used to mock the IParam objects as so:
`autosub.Resolve<IParam>() ... Returns( ... )`

When `ParamCollection` is resolved its constructor receives an empty list:
`autosub.Resolve<ParamCollection>()`

If however the constructor of ParamCollection is changed to take IEnumerable then when `ParamCollection` is resolved it receives correctly the list of objects which implements `IParam`.
`public class ParamCollection { public ParamCollection(IEnumerable<IParam> parameters) ... }`

The read only collection type is introduced with .NET framework 4.5:
https://visualstudiomagazine.com/articles/2012/08/07/new-read-only-collection-interfaces-for-net.aspx

I have attached a small test project to demonstrate:
[IReadOnlyCollectionTest.zip](https://github.com/MRCollective/AutofacContrib.NSubstitute/files/731405/IReadOnlyCollectionTest.zip)

**Comment by robdmoore** [comment]
Ah yeah - that makes sense.

Assuming the latest version of autofac supports read only collections you should be able to upgrade the projects to .net4.5.2 and upgrade nsubstitute and autofac. Feel free to send a PR for that change and I'll release it

**Comment by Jason-eCargo** [comment]
It appears there is already one in the pipeline:
https://github.com/MRCollective/AutofacContrib.NSubstitute/pull/24

**Comment by robdmoore** [comment]
Awkward!

I'll try and take a look.

I had a new son a couple of months ago so been a bit hectic.

**Comment by Jason-eCargo** [comment]
Congrats!

Absolutely no rush, just good to know it is in the pipeline.

**Comment by BrainCrumbz** [comment]
Congratulations!!!

**Comment by robdmoore** [comment]
:)

**Comment by Jason-eCargo** [comment]
Looks like it's not quite there yet, I will investigate a fix.

**Comment by robdmoore** [comment]
This is deployed to 4.0.1
