### ISSUE TITLE
Support for netcore?

### ISSUE THREAD

**Issue by grokky1** [MRCollective/AutofacContrib.NSubstitute#27]
Does this support .NET Core? I hope I'm not doing things wrong.

I get the error: `The dependency AutofacContrib.NSubstitute 4.0.1 does not support framework .NETCoreApp,Version=v1.1.`

**Comment by robdmoore** [comment]
No, sorry. Happy to receive a pull request to convert it over though.

I'm not sure if NSubstitute supports .net core? I know autofac does.

--

**Comment by grokky1** [comment]
Yes NSubstitute supports Core now.

PR: I'll try see if I can figure out how to do that. I only support Core, whereas I see most libs support multiple targets. I'm sure I can hack it to work on Core, but I assume you want it to remain backwards compatible, and I'm not sure how to do that unfortunately.
