### ISSUE TITLE
.net core and multi-targeting

### ISSUE THREAD

**Issue by jjafuller** [MRCollective/AutofacContrib.NSubstitute#28]
I'm working on getting a multi-targeting build put together, and my sticking point is the lack of nunit support for the current csproj format. How would you feel about converting the test suite to xunit as part of the pull request?

**Comment by robdmoore** [comment]
Fine by me

**Comment by jjafuller** [comment]
Are you cool with me forking this on nuget so that I can start using the version that supports .net core in my projects without manually dragging around the dll?

**Comment by jjafuller** [comment]
In the mean time we just incorporated it into our internal nuget repo.

**Comment by Ciget** [comment]
Hi guys, 
Is there any expected date when it`s possible to use this package for .net core 2.0?

**Comment by mozerov** [comment]
Hi guys, any news about this PR?

**Comment by mtrtm** [comment]
Hi all - I believe this issue would be solved if we got my PR done: https://github.com/MRCollective/AutofacContrib.NSubstitute/pull/35

It targets standard, so framework 4.6.1 and core 2.2 and up would work.  That should be sufficient AFAIK, but if it's not let me know
