### ISSUE TITLE
Concrete implementations don't work anymore with Autofac 4.9.0+

### ISSUE THREAD

**Issue by pratikf** [MRCollective/AutofacContrib.NSubstitute#34]
Hi,

I upgraded Autofac to 4.9.2 and concrete implementations don't work anymore; any resolve calls result in proxy creation. AutofacContrib.NSubstitute.Tests also fail related unit tests when upgraded to Autofac 4.9.0 or later.

```
            var container = new AutoSubstitute(builder =>
            {
                builder.RegisterType<MyProvider>().AsImplementedInterfaces().SingleInstance();
            });
            container.Provide<IProvider, MyProvider>();
            var provider = container.Resolve<IProvider>();
            // provider is a proxy
```

**Comment by Jason-eCargo** [comment]
I have a fix for it here: https://github.com/MRCollective/AutofacContrib.NSubstitute/pull/35

**Comment by bartecargo** [comment]
This bug is preventing us from upgrading Autofac. Is there any chance that the fix could be merged and a new version published to NuGet?

**Comment by mtrtm** [comment]
I'd love to see this project upgraded.  We are switching to .net core 3.1 (LTS) and it would be great to have this be compatible with all the latest stuff.

**Comment by mtrtm** [comment]
This will also work if https://github.com/MRCollective/AutofacContrib.NSubstitute/pull/37 is completed.  @bartecargo if you'd like to grab my fork and build locally, you can test.  You'll see the nuspec under the Debug folder when you build.  You can add a local nuget source and switch to 4.9.4.

**Comment by bartecargo** [comment]
@mtrtm If we don't get buy-in from the owner, who seems to have moved on from this project, we won't be able to merge any PRs.

**Comment by mtrtm** [comment]
@bartecargo the owners completed my PR, made the 5.0 package available, and I can now help on this project as well.  This now works for me using the latest package.  Please confirm and I will close the issue.

**Comment by bartecargo** [comment]
@mtrtm I've upgraded to the latest version, and it seems to be working well. Thanks!
