### ISSUE TITLE
TypeLoadException after upgrading to AutoFac6 and v6.2.2

### ISSUE THREAD

**Issue by vt92724023** [MRCollective/AutofacContrib.NSubstitute#62]
I get this in all my tests now whenever calling` new AutoSubstitute();` or `AutoSubstitute.Configure().Build();`

System.TypeLoadException : Method 'RegistrationsFor' in type 'AutofacContrib.NSubstitute.NSubstituteRegistrationHandler' from assembly 'AutofacContrib.NSubstitute, Version=4.9.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at AutofacContrib.NSubstitute.AutoSubstituteBuilder.InternalBuild()
   at AutofacContrib.NSubstitute.AutoSubstituteBuilder.Build()

NB: I notice that the assembly version reported by v6.2.2 and earlier package versions as well is always 4.9.4.0 ?

**Comment by twsouthwick** [comment]
That's an issue with autofac 6. #53 is tracking that. I'll get the fix out for that

**Comment by vt92724023** [comment]
I pulled the build of issue #53 and I can confirm it fixed this issue for me. I'm now getting this error, but for a much smaller number of tests

System.MissingMethodException : Method not found: 'System.__Canon NSubstitute.Arg.Any()'.
   at NSubstitute.NSubstituteDbSetExtensions.SetupData[TEntity](DbSet`1 dbSet, ICollection`1 data, Func`2 find)

When can we expect a nuget package release for v7?

**Comment by twsouthwick** [comment]
It's released now
